# SOPS configuration for secrets encryption
# Replace the age key with your own public key
# Generate with: age-keygen -o keys.txt
keys:
  - &primary age1your_public_key_here
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
